import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props:any) {
  const { children } = props;
 
  return (
      <html lang="ja">
        <body className={inter.className}>
          <main>{children}</main>
        </body>
      </html>
  )
}
